'use strict';

require('angular').module('capi-ui')
.controller('AddFieldCtrl', require('./AddFieldCtrl'))
.controller('CredentialsCtrl', require('./CredentialsCtrl'))
.controller('FieldOverviewCtrl', require('./FieldOverviewCtrl'))
.controller('HomeCtrl', require('./HomeCtrl'))
.controller('FlowOverviewCtrl', require('./FlowOverviewCtrl'))
.controller('FormOverviewCtrl', require('./formOverviewCtrl'))
.controller('MailTemplateCtrl', require('./mailTemplatesCtrl'))
.controller('MailTemplatesImportCtrl', require('./MailTemplatesImportCtrl'))
.controller('MailTemplatesExportCtrl', require('./MailTemplatesExportCtrl'))
.controller('SaveButtonCtrl', require('./SaveButtonCtrl'))
.controller('TranslationsCtrl', require('./translationsCtrl'))
.controller('RegionsCtrl', require('./RegionsCtrl'))
.controller('SchemaOverviewCtrl', require('./SchemaOverviewCtrl'))
.controller('AttributeOverviewCtrl', require('./AttributeOverviewCtrl'))
.controller('AttributeCreatorCtrl', require('./AttributeCreatorCtrl'))
.controller('AttributeCreatorFormCtrl', require('./AttributeCreatorFormCtrl'))
.controller('NotificationsCtrl', require('./NotificationsCtrl'))
